/**
 * Plan Mode Extension
 *
 * Read-only exploration mode for safe code analysis.
 * When enabled, only read-only tools are available.
 *
 * Features:
 * - /plan command or Ctrl+Alt+P to toggle
 * - Bash restricted to allowlisted read-only commands
 * - Extracts numbered plan steps from "Plan:" sections
 * - `plan_step_done` tool for the model to mark steps complete during execution
 * - [DONE:n] text markers as a fallback completion mechanism (still parsed)
 * - Progress tracking widget during execution
 * - Post-compaction auto-resume with plan state injection
 */

import type { AgentMessage } from "@earendil-works/pi-agent-core";
import type { AssistantMessage, TextContent } from "@earendil-works/pi-ai";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Key, Text } from "@earendil-works/pi-tui";
import { writeFileSync } from "node:fs";
import { Type } from "typebox";
import { blockReason, extractTodoItems, markCompletedSteps, type TodoItem } from "./utils.ts";

/** Tool name for the step-completion tool, also used in active-tool management. */
const PLAN_STEP_DONE_TOOL = "plan_step_done";

// Local addition (see AUDIT.md): persist a captured plan to a timestamped
// markdown file in cwd so plans are auditable artifacts, not just session state.
function writePlanToFile(planText: string): string {
	const now = new Date();
	const ts = now.toISOString().replace(/[:.]/g, "-");
	const path = `PLAN-${ts}.md`;
	const header = `# Plan — ${now.toISOString()}\n\n_Generated by pi plan-mode extension._\n\n---\n\n`;
	writeFileSync(path, header + planText.trim() + "\n");
	return path;
}

// Tools
const PLAN_MODE_TOOLS = ["read", "bash", "grep", "find", "ls", "questionnaire"];

/** Add the plan_step_done tool to a tools list (if not already present). */
function withPlanStepDone(tools: string[]): string[] {
	return tools.includes(PLAN_STEP_DONE_TOOL) ? tools : [...tools, PLAN_STEP_DONE_TOOL];
}

/** Remove the plan_step_done tool from a tools list. */
function withoutPlanStepDone(tools: string[]): string[] {
	return tools.filter((t) => t !== PLAN_STEP_DONE_TOOL);
}
// Built-in tools disabled in plan mode. Everything else that is currently active
// (e.g. Hindsight memory tools) stays available so the agent can recall/retain
// context while planning. NOTE: the bash allowlist (utils.ts) only constrains
// SHELL commands to local read-only; it does not sandbox the preserved tools.
// Injected tools keep their own capabilities and may perform network/side-
// effecting I/O. Plan mode disables built-in edit/write — not all egress.
const PLAN_MODE_DISABLED_TOOLS = new Set<string>(["edit", "write"]);

// Plan-mode tool set = the current active tools minus the disabled built-ins,
// with the read-only baseline guaranteed present. Preserves injected tools.
function getPlanModeTools(activeTools: string[]): string[] {
	return [...new Set([...activeTools.filter((t) => !PLAN_MODE_DISABLED_TOOLS.has(t)), ...PLAN_MODE_TOOLS])];
}

// Type guard for assistant messages
function isAssistantMessage(m: AgentMessage): m is AssistantMessage {
	return m.role === "assistant" && Array.isArray(m.content);
}

// Extract text content from an assistant message
function getTextContent(message: AssistantMessage): string {
	return message.content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join("\n");
}

export default function planModeExtension(pi: ExtensionAPI): void {
	let planModeEnabled = false;
	let executionMode = false;
	let todoItems: TodoItem[] = [];
	/** Snapshot of active tools before plan mode was enabled. */
	let normalModeTools: string[] | null = null;
	// Dedupe block notifications: skip notifying if the same command was just blocked
	// (the model often retries a rejected command several times).
	let lastBlockedCommand: string | null = null;

	// ── plan_step_done tool ──────────────────────────────────────────────
	// Registers a structured tool the model can call to mark a plan step as
	// complete, replacing the ad-hoc [DONE:N] text-marker hack (RC1/RC6).
	// The tool is always registered but only added to the active tool set
	// during execution mode (see withPlanStepDone / withoutPlanStepDone).
	// [DONE:N] text parsing is kept as a fallback for backward compatibility.
	pi.registerTool({
		name: PLAN_STEP_DONE_TOOL,
		label: "Plan Step Done",
		description:
			"Mark a plan step as completed during plan execution. Call this immediately after finishing a step. Returns current progress and the next step to work on.",
		promptSnippet: "Mark a plan step as complete (call after finishing each step).",
		promptGuidelines: [
			"After completing each plan step, call plan_step_done with the step number. Do not wait — call it as soon as the step is done.",
		],
		parameters: Type.Object({
			step: Type.Number({ description: "The step number to mark as completed (1-based, matching the plan numbering)" }),
		}),

		async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
			if (!executionMode || todoItems.length === 0) {
				return {
					content: [{ type: "text", text: "Not currently executing a plan. No steps to mark." }],
				};
			}

			const item = todoItems.find((t) => t.step === params.step);
			if (!item) {
				return {
					content: [
						{ type: "text", text: `Step ${params.step} not found. Valid steps: 1-${todoItems.length}.` },
					],
				};
			}

			const wasAlreadyDone = item.completed;
			item.completed = true;

			const completed = todoItems.filter((t) => t.completed).length;
			const remaining = todoItems.filter((t) => !t.completed);
			const allDone = remaining.length === 0;

			updateStatus(ctx);
			persistState(); // State changed — persist (RC2: only persist on change)

			if (allDone) {
				return {
					content: [
						{
							type: "text",
							text: `Step ${params.step} ${wasAlreadyDone ? "was already done" : "marked complete"}. All ${todoItems.length} steps completed! Plan is finished.`,
						},
					],
				};
			}

			const next = remaining[0];
			const nextText = next.rawText ?? next.text;
			return {
				content: [
					{
						type: "text",
						text: `Step ${params.step} ${wasAlreadyDone ? "was already done" : "marked complete"}. Progress: ${completed}/${todoItems.length}. Next: Step ${next.step}: ${nextText}`,
					},
				],
			};
		},

		renderCall(args, theme) {
			return new Text(
				theme.fg("toolTitle", theme.bold("plan_step_done ")) + theme.fg("accent", `step ${args.step}`),
				0,
				0,
			);
		},

		renderResult(result, _opts, theme) {
			const text = result.content[0];
			return new Text(theme.fg("success", "✓ ") + theme.fg("muted", text?.type === "text" ? text.text : ""), 0, 0);
		},
	});

	pi.registerFlag("plan", {
		description: "Start in plan mode (read-only exploration)",
		type: "boolean",
		default: false,
	});

	function updateStatus(ctx: ExtensionContext): void {
		// Footer status
		if (executionMode && todoItems.length > 0) {
			const completed = todoItems.filter((t) => t.completed).length;
			ctx.ui.setStatus("plan-mode", ctx.ui.theme.fg("accent", `📋 ${completed}/${todoItems.length}`));
		} else if (planModeEnabled) {
			ctx.ui.setStatus("plan-mode", ctx.ui.theme.fg("warning", "⏸ plan"));
		} else {
			ctx.ui.setStatus("plan-mode", undefined);
		}

		// Widget showing todo list
		if (executionMode && todoItems.length > 0) {
			const lines = todoItems.map((item) => {
				if (item.completed) {
					return (
						ctx.ui.theme.fg("success", "☑ ") + ctx.ui.theme.fg("muted", ctx.ui.theme.strikethrough(item.text))
					);
				}
				return `${ctx.ui.theme.fg("muted", "☐ ")}${item.text}`;
			});
			ctx.ui.setWidget("plan-todos", lines);
		} else {
			ctx.ui.setWidget("plan-todos", undefined);
		}
	}

	function togglePlanMode(ctx: ExtensionContext): void {
		planModeEnabled = !planModeEnabled;
		executionMode = false;
		todoItems = [];
		lastBlockedCommand = null;

		if (planModeEnabled) {
			// Snapshot current tools so we can restore them exactly on exit.
			// This preserves any tools injected by core or other extensions.
			// Filter out plan_step_done — it should not be in the snapshot since
			// we're leaving execution mode (if we were in it).
			normalModeTools = withoutPlanStepDone(pi.getActiveTools());
			pi.setActiveTools(getPlanModeTools(normalModeTools));
			ctx.ui.notify("Plan mode enabled. Built-in edit/write disabled; other tools (incl. memory) preserved.");
		} else {
			const restore = withoutPlanStepDone(normalModeTools ?? ["read", "bash", "edit", "write", "grep", "find", "ls", "questionnaire"]);
			pi.setActiveTools(restore);
			normalModeTools = null;
			ctx.ui.notify("Plan mode disabled. Full access restored.");
		}
		updateStatus(ctx);
	}

	function persistState(): void {
		pi.appendEntry("plan-mode", {
			enabled: planModeEnabled,
			todos: todoItems,
			executing: executionMode,
		});
	}

	/**
	 * Tear down execution mode: post a summary, clear the progress widget, and
	 * restore the pre-plan tool set. Used both when every step is tagged [DONE:n]
	 * and when the user explicitly finalizes a run that left steps untagged.
	 */
	function finalizePlan(ctx: ExtensionContext, allDone: boolean): void {
		const summary = todoItems.map((t) => (t.completed ? `~~${t.text}~~` : `☐ ${t.text}`)).join("\n");
		const header = allDone ? "**Plan Complete!** ✓" : "**Plan execution ended.**";
		pi.sendMessage(
			{ customType: "plan-complete", content: `${header}\n\n${summary}`, display: true },
			{ triggerTurn: false, deliverAs: "followUp" },
		);
		executionMode = false;
		todoItems = [];
		// Execution always runs in normal (non-plan) mode — the Execute branch exited
		// plan mode and restored tools when execution began — so the live tool set is
		// already correct, including anything injected by core/other extensions. Fall
		// back to the live set (not a hardcoded list) so we never clobber injected
		// tools (e.g. Hindsight). normalModeTools is null in the normal flow; the ??
		// only guards a hypothetical non-null snapshot.
		// RC1 fix: remove the plan_step_done tool — it's only relevant during execution.
		const restore = withoutPlanStepDone(normalModeTools ?? pi.getActiveTools());
		pi.setActiveTools(restore);
		normalModeTools = null;
		updateStatus(ctx);
		persistState(); // Save cleared state so resume doesn't restore old execution mode
	}

	pi.registerCommand("plan", {
		description: "Toggle plan mode (read-only exploration)",
		handler: async (_args, ctx) => togglePlanMode(ctx),
	});

	pi.registerCommand("todos", {
		description: "Show current plan todo list",
		handler: async (_args, ctx) => {
			if (todoItems.length === 0) {
				ctx.ui.notify("No todos. Create a plan first with /plan", "info");
				return;
			}
			const list = todoItems.map((item, i) => `${i + 1}. ${item.completed ? "✓" : "○"} ${item.text}`).join("\n");
			ctx.ui.notify(`Plan Progress:\n${list}`, "info");
		},
	});

	pi.registerShortcut(Key.ctrlAlt("p"), {
		description: "Toggle plan mode",
		handler: async (ctx) => togglePlanMode(ctx),
	});

	// Block destructive bash commands in plan mode
	pi.on("tool_call", async (event, ctx) => {
		if (!planModeEnabled || event.toolName !== "bash") return;

		const command = event.input.command as string;
		const why = blockReason(command);
		if (why) {
			if (command !== lastBlockedCommand) {
				ctx.ui.notify(`⏸ Plan mode blocked (${why}): ${command}`, "warning");
				lastBlockedCommand = command;
			}
			return {
				block: true,
				reason: `Plan mode: ${why}. Use /plan to disable plan mode first.\nCommand: ${command}`,
			};
		}
		lastBlockedCommand = null;
	});

	// Filter out stale plan mode context when not in plan mode
	pi.on("context", async (event) => {
		if (planModeEnabled) return;

		return {
			messages: event.messages.filter((m) => {
				const msg = m as AgentMessage & { customType?: string };
				if (msg.customType === "plan-mode-context") return false;
				if (msg.role !== "user") return true;

				const content = msg.content;
				if (typeof content === "string") {
					return !content.includes("[PLAN MODE ACTIVE]");
				}
				if (Array.isArray(content)) {
					return !content.some(
						(c) => c.type === "text" && (c as TextContent).text?.includes("[PLAN MODE ACTIVE]"),
					);
				}
				return true;
			}),
		};
	});

	// Inject plan/execution context before agent starts
	pi.on("before_agent_start", async () => {
		if (planModeEnabled) {
			return {
				message: {
					customType: "plan-mode-context",
					content: `[PLAN MODE ACTIVE]
You are in plan mode - a read-only exploration mode for safe code analysis.

Restrictions:
- Built-in edit and write tools are disabled (no file modifications)
- Other active tools remain available (read, bash, grep, find, ls, questionnaire, memory tools)
- Bash is restricted to an allowlist of read-only, local shell commands (no network via the shell)
- Other active tools keep their normal capabilities (memory tools may read/write their own store)

Ask clarifying questions using the questionnaire tool.

Create a detailed numbered plan under a "Plan:" header:

Plan:
1. First step description
2. Second step description
...

Do NOT attempt to make changes - just describe what you would do.`,
					display: false,
				},
			};
		}

		if (executionMode && todoItems.length > 0) {
			// RC4/RC5 fix: inject a rich execution context that shows progress,
			// identifies the next step, and instructs the model to use the
			// plan_step_done tool. This fires on every user-initiated turn during
			// execution, including after compaction (non-overflow), giving the
			// model a reliable re-orientation point.
			const completed = todoItems.filter((t) => t.completed).length;
			const remaining = todoItems.filter((t) => !t.completed);
			const todoList = remaining.map((t) => `${t.step}. ${t.text}`).join("\n");
			const nextStep = remaining[0];
			const nextText = nextStep ? nextStep.rawText ?? nextStep.text : "(all steps complete)";
			return {
				message: {
					customType: "plan-execution-context",
					content: `[EXECUTING PLAN — Full tool access enabled]

Progress: ${completed}/${todoItems.length} steps completed.

Continue with step ${nextStep?.step ?? "?"}: ${nextText}

Remaining steps:
${todoList}

After completing a step, call the plan_step_done tool with the step number. Do not wait — call it as soon as the step is done. (You can also write [DONE:n] in your response as a fallback.)`,
					display: false,
				},
			};
		}
	});

	// Track progress after each turn.
	// RC2 fix: only persist (emit plan-mode event) when the completion state
	// actually changes. Previously persistState() ran on every turn_end,
	// emitting 90+ identical plan-mode entries that wasted ~1.3MB of context.
	pi.on("turn_end", async (event, ctx) => {
		if (!executionMode || todoItems.length === 0) return;
		if (!isAssistantMessage(event.message)) return;

		const text = getTextContent(event.message);
		if (markCompletedSteps(text, todoItems) > 0) {
			updateStatus(ctx);
			persistState(); // State changed — emit a plan-mode entry
		}
		// If nothing changed, do NOT persist. This is the RC2 fix.
	});

	// Handle plan completion and plan mode UI
	pi.on("agent_end", async (event, ctx) => {
		// Check if execution is complete
		if (executionMode && todoItems.length > 0) {
			const allDone = todoItems.every((t) => t.completed);
			// The agent run has gone idle. If every step carries a [DONE:n] tag we
			// finalize automatically (original behavior). If not, the model finished
			// the run without tagging every step (common) — without intervention the
			// progress widget would linger until some later turn happened to emit the
			// missing tag. Prompt the user instead of leaving a stale widget.
			if (!allDone && ctx.hasUI) {
				const completed = todoItems.filter((t) => t.completed).length;
				const choice = await ctx.ui.select(
					`Plan execution finished (${completed}/${todoItems.length} steps tagged done) — what next?`,
					["End execution (clear tracker)", "Keep tracking (still executing)"],
				);
				// State may have changed while the dialog was open.
				if (!executionMode) return;
				if (choice !== "End execution (clear tracker)") return;
			}
			finalizePlan(ctx, allDone);
			return;
		}

		if (!planModeEnabled || !ctx.hasUI) return;

		// Extract todos from last assistant message
		const lastAssistant = [...event.messages].reverse().find(isAssistantMessage);
		if (lastAssistant) {
			const planText = getTextContent(lastAssistant);
			const extracted = extractTodoItems(planText);
			if (extracted.length > 0) {
				todoItems = extracted;
				// Persist the full plan text to an auditable file in cwd.
				try {
					const path = writePlanToFile(planText);
					ctx.ui.notify(`Plan saved to ${path}`, "info");
				} catch (err) {
					ctx.ui.notify(`Could not save plan to file: ${err instanceof Error ? err.message : String(err)}`, "warning");
				}
			}
		}

		// No plan was produced (e.g. the model asked a clarifying question or only
		// explored) — stay in plan mode silently rather than prompting "what next?"
		// with nothing to execute.
		if (todoItems.length === 0) return;

		// Show plan steps and prompt for next action
		const todoListText = todoItems.map((t, i) => `${i + 1}. ☐ ${t.text}`).join("\n");
		pi.sendMessage(
			{
				customType: "plan-todo-list",
				content: `**Plan Steps (${todoItems.length}):**\n\n${todoListText}`,
				display: true,
			},
			{ triggerTurn: false, deliverAs: "followUp" },
		);

		const choice = await ctx.ui.select("Plan mode - what next?", [
			"Execute the plan (track progress)",
			"Stay in plan mode",
			"Refine the plan",
		]);

		// Guard: state may have changed while the select dialog was open (e.g.
		// user toggled plan mode via Ctrl+Alt+P shortcut).
		if (!planModeEnabled) return;

		if (choice?.startsWith("Execute")) {
			planModeEnabled = false;
			executionMode = true;
			const restore = normalModeTools ?? ["read", "bash", "edit", "write", "grep", "find", "ls", "questionnaire"];
			// RC1 fix: include the plan_step_done tool so the model can mark steps
			// complete via a structured tool call instead of [DONE:N] text markers.
			pi.setActiveTools(withPlanStepDone(restore));
			normalModeTools = null;
			updateStatus(ctx);
			persistState();

			// agent_end fires while the agent is still streaming, so this turn is
			// delivered via the follow-up queue and run through agent.continue() —
			// which does NOT re-fire before_agent_start. The execution context
			// (remaining steps + the plan_step_done instruction) must therefore be
			// inlined here; before_agent_start only injects it on later turns.
			const remaining = todoItems.map((t) => `${t.step}. ${t.text}`).join("\n");
			const execMessage = `Execute the plan.

Remaining steps:
${remaining}

Start with step ${todoItems[0].step}: ${todoItems[0].rawText ?? todoItems[0].text}
After completing a step, call the plan_step_done tool with the step number to mark it complete. Do not wait — call it as soon as the step is done.

Tip: For git commits with special characters in the message, use git commit -F <file> instead of -m to avoid shell interpretation errors.`;
			pi.sendMessage(
				{ customType: "plan-mode-execute", content: execMessage, display: true },
				{ triggerTurn: true, deliverAs: "followUp" },
			);
		} else if (choice === "Refine the plan") {
			const refinement = await ctx.ui.editor("Refine the plan:", "");
			// Guard: state may have changed while the editor dialog was open.
			if (!planModeEnabled) return;
			if (refinement?.trim()) {
				// agent_end still counts as streaming, so deliverAs is required to queue
				// the refinement as a follow-up turn instead of throwing.
				pi.sendUserMessage(refinement.trim(), { deliverAs: "followUp" });
			}
		}
	});

	// Re-anchor plan state across a compaction boundary. Compaction can summarize
	// away the older plan-mode entry, the plan-mode-execute marker, and the
	// [DONE:n]-tagged assistant messages that session_start re-scans on resume.
	// In-memory state (todoItems + completion) is authoritative for the live session
	// and survives compaction untouched, so re-persisting here writes a fresh
	// plan-mode entry AFTER the boundary; resume-after-compaction then reconstructs
	// todos and completion correctly. markCompletedSteps is additive, so a later
	// re-scan can only confirm — never clear — the restored completion.
	//
	// While executing we also re-emit a silent plan-mode-execute marker. The
	// resume re-scan bounds [DONE:n] scanning to entries after the last such
	// marker; if compaction summarizes the original marker away, executeIndex
	// falls back to -1 (scan from the start). That fallback is provably safe here
	// (chronological ordering means a lost marker implies all strictly-older DONE
	// tags are summarized too, and the summary entry is not an assistant message
	// so it is never scanned — see AUDIT.md), but re-anchoring the marker removes
	// the dependency on that invariant: the scan window stays explicitly bounded.
	//
	// We deliberately do NOT re-inject remaining steps for the overflow/willRetry
	// path. The retry runs via agent.continue(), which does not re-fire
	// before_agent_start, and extension messages (nextTurn is consumed only in
	// prompt(); followUp lands after the run) cannot reach that continuation's
	// context — verified against pi v0.79.10 agent-session.js (see AUDIT.md). The
	// overflowing turn's own plan-execution-context is the most-recent content and
	// is normally kept past firstKeptEntryId, and pi's summary captures
	// progress/next-steps, so the retry still sees the plan.
	pi.on("session_compact", async (event, ctx) => {
		const executing = executionMode && todoItems.length > 0;
		if (!planModeEnabled && !executing) return;

		persistState();
		if (executing) {
			// Re-establish the [DONE:n] scan boundary past the compaction point.
			pi.appendEntry("plan-mode-execute", { reanchored: true });
		}

		// RC4 fix: for manual compaction during execution, send a continuation
		// message with the current plan state so the model can auto-resume
		// without the user having to say "continue". For threshold compaction,
		// the run continues and before_agent_start will re-inject context on the
		// next turn. For overflow+willRetry, the retry handles it (see AUDIT.md).
		if (executing && event.reason === "manual") {
			const completed = todoItems.filter((t) => t.completed).length;
			const remaining = todoItems.filter((t) => !t.completed);
			const todoList = remaining.map((t) => `${t.step}. ${t.text}`).join("\n");
			const nextStep = remaining[0];
			const nextText = nextStep ? nextStep.rawText ?? nextStep.text : "(all steps complete)";
			const resumeMessage = `Context was compacted. Resume the plan.

Progress: ${completed}/${todoItems.length} steps completed.
Continue with step ${nextStep?.step ?? "?"}: ${nextText}

Remaining steps:
${todoList}

After completing a step, call the plan_step_done tool with the step number.`;
			pi.sendMessage(
				{ customType: "plan-mode-resume", content: resumeMessage, display: true },
				{ triggerTurn: true, deliverAs: "followUp" },
			);
		}

		if (!ctx.hasUI) return;
		const label =
			event.reason === "manual"
				? "manual /compact"
				: event.reason === "overflow"
					? event.willRetry
						? "overflow recovery — retrying"
						: "overflow"
					: "auto-compaction";
		if (executing) {
			const remaining = todoItems.filter((t) => !t.completed).length;
			ctx.ui.notify(`Context compacted (${label}) — ${remaining} plan step(s) remaining.`, "info");
		} else {
			ctx.ui.notify(`Context compacted (${label}) — still in plan mode.`, "info");
		}
	});

	// Restore state on session start/resume
	pi.on("session_start", async (event, ctx) => {
		// Apply --plan flag only on initial startup; on resume/fork/new the
		// persisted session state should take precedence.
		if (event.reason === "startup" && pi.getFlag("plan") === true) {
			planModeEnabled = true;
		}

		const entries = ctx.sessionManager.getEntries();

		// Restore persisted state
		const planModeEntry = entries
			.filter((e: { type: string; customType?: string }) => e.type === "custom" && e.customType === "plan-mode")
			.pop() as { data?: { enabled: boolean; todos?: TodoItem[]; executing?: boolean } } | undefined;

		if (planModeEntry?.data) {
			planModeEnabled = planModeEntry.data.enabled ?? planModeEnabled;
			todoItems = planModeEntry.data.todos ?? todoItems;
			executionMode = planModeEntry.data.executing ?? executionMode;
		}

		// On resume: re-scan messages to rebuild completion state
		// Only scan messages AFTER the last "plan-mode-execute" to avoid picking up [DONE:n] from previous plans
		const isResume = planModeEntry !== undefined;
		if (isResume && executionMode && todoItems.length > 0) {
			// Find the index of the last plan-mode-execute entry (marks when current execution started)
			let executeIndex = -1;
			for (let i = entries.length - 1; i >= 0; i--) {
				const entry = entries[i] as { type: string; customType?: string };
				if (entry.customType === "plan-mode-execute") {
					executeIndex = i;
					break;
				}
			}

			// Only scan messages after the execute marker
			const messages: AssistantMessage[] = [];
			for (let i = executeIndex + 1; i < entries.length; i++) {
				const entry = entries[i];
				if (entry.type === "message" && "message" in entry && isAssistantMessage(entry.message as AgentMessage)) {
					messages.push(entry.message as AssistantMessage);
				}
			}
			const allText = messages.map(getTextContent).join("\n");
			markCompletedSteps(allText, todoItems);
		}

		if (planModeEnabled) {
			// Snapshot current tools before restricting, so we can restore them
			// exactly when plan mode is disabled (preserves Hindsight tools, etc.).
			// Filter out plan_step_done — not relevant in plan mode.
			normalModeTools = withoutPlanStepDone(pi.getActiveTools());
			pi.setActiveTools(getPlanModeTools(normalModeTools));
		} else if (executionMode && todoItems.length > 0) {
			// RC1 fix: ensure plan_step_done is available when resuming mid-execution.
			const current = pi.getActiveTools();
			if (!current.includes(PLAN_STEP_DONE_TOOL)) {
				pi.setActiveTools(withPlanStepDone(current));
			}
		}
		updateStatus(ctx);
	});
}
